---
name: Tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONASYNCIODEBUG: 1
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start RabbitMQ
        run: |
          docker run -d -p 127.0.0.1:5672:5672 -p 127.0.0.1:15672:15672 \
            --name rabbitmq rabbitmq:3.9-management
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements_dev.txt
          python -m pip install --editable .
          python -m pip freeze
      - name: Run tests
        run: |
          make test
      - name: Run pylint
        run: |
          make pylint
      - name: Print RabbitMQ's logs
        run: |
          docker logs rabbitmq
        if: ${{ !cancelled() }}
